// <auto-generated />
namespace Social.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_elementid_type_to_int_from_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_elementid_type_to_int_from_string));
        
        string IMigrationMetadata.Id
        {
            get { return "201904061019154_change_elementid_type_to_int_from_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
